### ISSUE TITLE
AsyncEdgeInterpreter impl

### ISSUE THREAD

**Issue by Fristi** [ThomasMeijers/scala-oriented#12]
https://github.com/ThomasMeijers/scala-oriented/blob/master/src/main/scala/oriented/free/interpreters/EdgeInterpreter.scala#L73

`Future` has a `Try` built in, no need to create a safe variant of that. You can also create Future from a try by using `Future.fromTry`

**Comment by ItsMeijers** [comment]
I shall have a look into it. Thanks 👍
